import { createSlice } from "@reduxjs/toolkit";
import { reset } from "../action";

const moviesSlice = createSlice({
  name: "movie",
  initialState: [],
  reducers: {
    addMovie(state, action) {
      state.push(action.payload);
    },
    removeMovie(state, action) {
      const index = state.indexOf(action.payload);
      state.splice(index, 1);
    },
  },
  extraReducers(builder){
    builder.addCase(reset, (state, action) => { 
      return[];
    });
  }
});

export const {addMovie, removeMovie} = moviesSlice.actions;
export const moviesReducer = moviesSlice.reducer; // No curly braces because we are not destructuring anything like above 

// Lets understand extraReducers
// In Redux Toolkit's createSlice function, extraReducers is an optional builder callback. It allows you to define additional reducers that don't directly correspond to actions generated by the slice.
// builder is a parameter provided to the callback function passed to extraReducers. It is an object that exposes methods like addCase, addDefaultCase and addMatcher to define additional reducers. The builder object helps organize and add extra reducers in a clean and readable way. Lets focus only on 'addCase' and not worry about others.
  // {addCase: ƒ, addMatcher: ƒ, addDefaultCase: ƒ}
    // addCase: ƒ addCase(typeOrActionCreator, reducer)
    // addDefaultCase: ƒ addDefaultCase(reducer)
    // addMatcher: ƒ addMatcher(matcher, reducer)
    // [[Prototype]]: Object
// As we can see, in addCase first argument is the action-type and second argument is the reducer.
// The addCase method is used to add an extra reducer. It takes two parameters:
  // The action type (reset in this case).
  // A callback function that specifies how the state should be updated in response to the action.
    // The callback is simply a mini-reducer function like addSong/removeSong 
    // Whenver reset is triggered (first argument), execute the reducer (second argument) 
// Though 'extrareducers' and 'Builder' are not keywords with respect to react, redux treat it like one. So you can't alter them.
// You can simply define the function within reducers itself right? There is no need for extraReducers as they dont improve performance or efficiency and their primary purpose is to improve readability by separating the functions. But technically, they do exists for a reason.
  // When we want an action type that is being dispatched from somewhere else to alter our mini-state under createSlice, then those functions are typically placed under extraReducers. For example, if a particular event triggered by a user, where multiple states need to be altered, we generally dispatch a common action type for all those states to perform a coordinated action. (reset in our case)

// Some more explanation for additional clarity 
// builder.addCase(reset, (state, action) => {
  // reset is an action-type that we have created in 'action' component and imported here 
  // reducer() is the second argument. It is no different from what we have seen already. 
  // Basically, reset is a variable that holds the action object based on the below statement that we have it in 'action' component
    // const reset = createAction ('app/reset');
    // reset has the type: app/reset and payload: undefined
  // Now when we dispatch(reset) and the user clicks reset button, reducer() will be called with action type app/reset as its argument. This is the command that we are providing the action object within reducer.  
  
// When you use createSlice, it automatically generates action types and action creators (objects) based on the reducers defined in the reducers object.
// The action types are strings representing the types of actions that can be dispatched.
// But, when you use builder.addCase within extraReducers, you are specifying how the slice should respond to certain action types that are not defined within the current slice.
// The action type (e.g., 'RESET') is expected to be dispatched from elsewhere in the application.

// Note: Even though action creators are automatically created by createSlice in Redux Toolkit, you need to explicitly export them if you want to use them elsewhere in your application.
